/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Notify: typeof import('./src/components/Notify.vue')['default']
    NutBadge: typeof import('@nutui/nutui')['Badge']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutNoticebar: typeof import('@nutui/nutui')['Noticebar']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    Tab: typeof import('./src/components/Tab.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
