/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NutBadge: typeof import('@nutui/nutui')['Badge']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
  }
}
